# This file creates a conda environment for the guppy module
#   conda env create -f environment.yml
name: nfcore-module-tobias
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - pysam=0.16.0.1
  - pybigwig=0.3.17
  - samtools=1.11
  - moods=1.9.4.1
  - pybedtools=0.8.1
  - bedtools=2.29.2
  - cython=0.29.21
  - matplotlib=3.3.2
  - numpy=1.19.2
  - scipy=1.5.2
  - pypdf2=1.26.0
  - scikit-learn=0.23.2
  - svist4get=1.2.22
  - pyyaml=5.3.1
  - boto3=1.15.16
  - adjustText=0.7.3.1
  - sklearn-contrib-lightning=0.5.0
  - xlsxwriter=1.3.7
  - pip
  - pip:
    - gimmemotifs==0.15.0